version: 2

general:
  branches:
    ignore:
      - gh-pages
    only:
     - master

jobs:
  build:
    docker:
      - image: node:20.16.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
      - run: git config --global user.name "$GH_NAME" > /dev/null 2>&1
#      - run: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
